# Generated by Django 5.1.13 on 2025-11-17 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hand_made', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='email',
            field=models.EmailField(max_length=20),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='name',
            field=models.TextField(max_length=20),
        ),
    ]
